package com.aiknow.audit;

public enum AuditEventType {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    ORGANIZATION_CREATED,
    WORKSPACE_CREATED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    ROLE_CHANGED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    DOCUMENT_REPROCESSED,
    QUESTION_ASKED
}
